#!/usr/bin/env python3
"""
Student Management System MCP Server (v2.0 - Real DB Version)

支持真正的数据库连接和 AI 辅助开发。
"""

from mcp.server import Server
from mcp.types import Tool, TextContent
import json
import os
from pathlib import Path
from sqlalchemy import create_engine, text
from sqlalchemy.exc import SQLAlchemyError
from dotenv import load_dotenv

# 加载环境变量 (从 .env 文件读取数据库连接)
load_dotenv()
DB_URL = os.getenv("DB_URL", "mysql+pymysql://root:password@localhost:3306/student_management")

# 初始化 MCP Server
server = Server("student-management-mcp")

# 项目根目录
PROJECT_ROOT = Path(__file__).parent.parent
SRC_ROOT = PROJECT_ROOT / "src" / "main" / "java" / "com" / "student"

# 数据库引擎
try:
    engine = create_engine(DB_URL)
except Exception as e:
    print(f"Error creating engine: {e}")
    engine = None

# ----------------- 资源 (Resources) -----------------

@server.list_resources()
async def list_resources() -> list:
    return [
        {
            "uri": "database://schema",
            "name": "数据库架构 (Real-Time)",
            "description": "系统当前的数据库结构信息",
            "mimeType": "application/json",
        }
    ]

@server.read_resource()
async def read_resource(uri: str) -> str:
    if uri == "database://schema" and engine:
        # 简单模拟返回架构，实际可以从引擎读取
        return json.dumps({"status": "connected", "database": engine.url.database}, indent=2)
    return "Resource not found or database not connected"

# ----------------- 工具 (Tools) -----------------

@server.list_tools()
async def list_tools() -> list[Tool]:
    return [
        Tool(
            name="execute_query",
            description="执行 SQL 查询并返回结果 (只读)",
            inputSchema={
                "type": "object",
                "properties": {
                    "sql": {"type": "string", "description": "要执行的 SQL 语句"}
                },
                "required": ["sql"]
            }
        ),
        Tool(
            name="audit_java_code",
            description="对本地 Java 文件进行代码质量和业务逻辑审计",
            inputSchema={
                "type": "object",
                "properties": {
                    "file_path": {"type": "string", "description": "Java 文件路径"}
                },
                "required": ["file_path"]
            }
        ),
        Tool(
            name="generate_tutoring_plan",
            description="为不及格学生自动生成针对性的 AI 补习计划",
            inputSchema={
                "type": "object",
                "properties": {
                    "student_name": {"type": "string", "description": "学生姓名"},
                    "major": {"type": "string", "description": "专业名称"},
                    "score": {"type": "number", "description": "当前成绩"}
                },
                "required": ["student_name", "major", "score"]
            }
        )
    ]

@server.call_tool()
async def call_tool(name: str, arguments: dict) -> list[TextContent]:
    if name == "execute_query":
        # ... (原有逻辑)
        pass
    
    elif name == "audit_java_code":
        # ... (原有逻辑)
        pass

    elif name == "generate_tutoring_plan":
        name = arguments.get("student_name")
        major = arguments.get("major")
        score = arguments.get("score")
        return [TextContent(type="text", text=generate_tutoring_plan_impl(name, major, score))]
    
    return [TextContent(type="text", text=f"Unknown tool: {name}")]

# ----------------- 逻辑实现 (Implementations) -----------------

def generate_tutoring_plan_impl(name: str, major: str, score: float) -> str:
    """生成补习计划的 Prompt 模板"""
    plan = f"""
# 🎓 针对性补习计划 (Targeted Tutoring Plan)
**学生**：{name}  **专业**：{major}  **当前成绩**：{score} (RED ALERT)

## 🎯 补习目标：
在 7 天内将核心知识点从 0 补齐到 60+。

## 📅 七天冲刺安排：
- **Day 1-2: 基础扫盲**
  重点补齐 {major} 专业中占比 40% 的最基础概念。
- **Day 3-4: 错题精讲**
  利用 AI 模拟面试，针对典型易错题进行专项训练。
- **Day 5: 考点押题**
  结合往年考纲，模拟 2 套试卷。
- **Day 6: 心理疏导与查缺补漏**
  与 AI 辅导员进行一次全真考场压力模拟。
- **Day 7: 正式考核**

## 💡 给辅导员的建议：
该生目前状态处于 [低动力/高焦虑] 状态，建议在约谈时多给予正向激励。

---
*Generated by Student Management AI System.*
"""
    return plan

def execute_sql_impl(sql: str) -> str:
    if not engine:
        return "数据库未连接，请检查 .env 配置。"
    try:
        with engine.connect() as conn:
            result = conn.execute(text(sql))
            rows = [dict(zip(result.keys(), row)) for row in result]
            return json.dumps(rows, ensure_ascii=False, indent=2, default=str)
    except SQLAlchemyError as e:
        return f"SQL Error: {str(e)}"

def audit_code_impl(file_path: str) -> str:
    # 逻辑简化：实际会读取文件并结合 LLM 审计
    full_path = SRC_ROOT / file_path
    if not full_path.exists():
        return f"错误：未找到文件 {file_path}"
    
    with open(full_path, "r", encoding="utf-8") as f:
        content = f.read()
    
    # 模拟审计结果
    issues = []
    if "age" in content and "max" not in content:
        issues.append("⚠️ 年龄字段缺少边界值验证。")
    if "Connection" in content and ".close()" not in content:
        issues.append("❌ 数据库连接可能未正确关闭，存在内存泄漏风险。")
    
    return "代码审计完成：\n" + ("\n".join(issues) if issues else "✅ 未发现明显业务逻辑漏洞。")

# ----------------- 启动 -----------------

async def main():
    import asyncio
    from mcp.server.stdio import stdio_server
    async with stdio_server() as (read_stream, write_stream):
        await server.run(read_stream, write_stream, server.create_initialization_options())

if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
